### ISSUE TITLE
Windows executable doesn't accept -template flag

### ISSUE THREAD

**Issue by goatlady** [wttw/markdownish#1]
I downloaded the windows executable, unzipped mdtohtml.exe and copied to my user directory (Windows 10 Home 64bit, 20H2 version build 19042.867 - Go is installed) along with a sample md file, (bartek.md) and the plain.gotext template file from the source code zip. 

From PowerShell, ran 

`mdtohtml -template plain.gotext bartek.md bartek.html`

Got the message "flag provided but not defined: -template" followed by the regular copyright, usage and options help.

I also tried running the executable from within the markdownish-0.1 directory in my user directory, same issue. 

Running main.go with the same parameters works fine.

**Comment by wttw** [comment]
I can't replicate it here with any combo of parameters, with `-template` or `--template` in either powershell or a cmd prompt.

That's the default error when passing an invalid flag, so `.\mdtohtml -templat` would give `flag provided but not defined: -templat`.

🤷‍♂️

**Comment by goatlady** [comment]
I dunno either, ha. I had already pulled down the gomarkdown project and been playing with the scripts there (although not the executable version), so maybe it was trying to run the wrong one? I will try it on another machine here with nothing else installed.

**Comment by wttw** [comment]
Oh, could be. If you did a build from source in a typical Go environment it would have added the (half-baked) binary to somewhere in your PATH. Try running it with an explicit path, or `.\mdtohtml -template plain.gotext bartek.md bartek.html` and see if that's the issue.

(Adding a `-version` flag is probably a good idea...)

**Comment by goatlady** [comment]
Issue disappeared when I cleaned up my install :)
